[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
yew = "0.19"
yew-router = "0.16"
common = { path = "../common", features = ["js"] }
reqwasm = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
