[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
uuid = { version = "1.1", features = ["v4"] }

[features]
js = ["uuid/js"]
