name: build
on:
  push:
    branches:
      - master

jobs:
  build-server:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build server
        working-directory: ./backend
        run: cargo build --release

      - name: Upload artifacts (Unix-like only)
        uses: actions/upload-artifact@v3
        if: matrix.platform != 'windows-latest'
        with:
          name: server-${{ matrix.platform }}
          path: target/release/app

      - name: Upload artifacts (Windows only)
        uses: actions/upload-artifact@v3
        if: matrix.platform == 'windows-latest'
        with:
          name: server-${{ matrix.platform }}
          path: target/release/app.exe

  build-app:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: stable

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: trunk wasm-bindgen-cli

      - name: Install Tauri dependencies
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: tauri-cli --locked --version "^1.0.0-rc"

      - name: Build App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tauriScript: cargo tauri

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-${{ matrix.platform }}
          path: target/release/bundle/
